//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace CiaranONeill.NPV.Silverlight.NpvDateServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolloverType", Namespace="http://schemas.datacontract.org/2004/07/CiaranONeill.NPV.Calculator")]
    public enum RolloverType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annual = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quarter = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="NpvDateServiceReference.NpvDateService")]
    public interface NpvDateService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:NpvDateService/GetDates", ReplyAction="urn:NpvDateService/GetDatesResponse")]
        System.IAsyncResult BeginGetDates(CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<System.DateTime> EndGetDates(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NpvDateServiceChannel : CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<System.DateTime> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<System.DateTime>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NpvDateServiceClient : System.ServiceModel.ClientBase<CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService>, CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService {
        
        private BeginOperationDelegate onBeginGetDatesDelegate;
        
        private EndOperationDelegate onEndGetDatesDelegate;
        
        private System.Threading.SendOrPostCallback onGetDatesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public NpvDateServiceClient() {
        }
        
        public NpvDateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NpvDateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpvDateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpvDateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDatesCompletedEventArgs> GetDatesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService.BeginGetDates(CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDates(period, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<System.DateTime> CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService.EndGetDates(System.IAsyncResult result) {
            return base.Channel.EndGetDates(result);
        }
        
        private System.IAsyncResult OnBeginGetDates(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period = ((CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType)(inValues[0]));
            return ((CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService)(this)).BeginGetDates(period, callback, asyncState);
        }
        
        private object[] OnEndGetDates(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<System.DateTime> retVal = ((CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService)(this)).EndGetDates(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDatesCompleted(object state) {
            if ((this.GetDatesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDatesCompleted(this, new GetDatesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDatesAsync(CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period) {
            this.GetDatesAsync(period, null);
        }
        
        public void GetDatesAsync(CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period, object userState) {
            if ((this.onBeginGetDatesDelegate == null)) {
                this.onBeginGetDatesDelegate = new BeginOperationDelegate(this.OnBeginGetDates);
            }
            if ((this.onEndGetDatesDelegate == null)) {
                this.onEndGetDatesDelegate = new EndOperationDelegate(this.OnEndGetDates);
            }
            if ((this.onGetDatesCompletedDelegate == null)) {
                this.onGetDatesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDatesCompleted);
            }
            base.InvokeAsync(this.onBeginGetDatesDelegate, new object[] {
                        period}, this.onEndGetDatesDelegate, this.onGetDatesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService CreateChannel() {
            return new NpvDateServiceClientChannel(this);
        }
        
        private class NpvDateServiceClientChannel : ChannelBase<CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService>, CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService {
            
            public NpvDateServiceClientChannel(System.ServiceModel.ClientBase<CiaranONeill.NPV.Silverlight.NpvDateServiceReference.NpvDateService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetDates(CiaranONeill.NPV.Silverlight.NpvDateServiceReference.RolloverType period, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = period;
                System.IAsyncResult _result = base.BeginInvoke("GetDates", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<System.DateTime> EndGetDates(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<System.DateTime> _result = ((System.Collections.ObjectModel.ObservableCollection<System.DateTime>)(base.EndInvoke("GetDates", _args, result)));
                return _result;
            }
        }
    }
}
