//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace CiaranONeill.NPV.Silverlight.NpvServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NpvData", Namespace="http://schemas.datacontract.org/2004/07/CiaranONeill.NPV.Calculator")]
    public partial class NpvData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double CashflowField;
        
        private System.DateTime PeriodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cashflow {
            get {
                return this.CashflowField;
            }
            set {
                if ((this.CashflowField.Equals(value) != true)) {
                    this.CashflowField = value;
                    this.RaisePropertyChanged("Cashflow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolloverType", Namespace="http://schemas.datacontract.org/2004/07/CiaranONeill.NPV.Calculator")]
    public enum RolloverType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annual = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quarter = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="NpvServiceReference.NpvService")]
    public interface NpvService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:NpvService/GetRandomData", ReplyAction="urn:NpvService/GetRandomDataResponse")]
        System.IAsyncResult BeginGetRandomData(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<double> EndGetRandomData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:NpvService/CalculateNpv", ReplyAction="urn:NpvService/CalculateNpvResponse")]
        System.IAsyncResult BeginCalculateNpv(System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData, double rate, CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType, bool useXnpvFormula, System.AsyncCallback callback, object asyncState);
        
        double EndCalculateNpv(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NpvServiceChannel : CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRandomDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRandomDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<double> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<double>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculateNpvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalculateNpvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NpvServiceClient : System.ServiceModel.ClientBase<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService>, CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService {
        
        private BeginOperationDelegate onBeginGetRandomDataDelegate;
        
        private EndOperationDelegate onEndGetRandomDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetRandomDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalculateNpvDelegate;
        
        private EndOperationDelegate onEndCalculateNpvDelegate;
        
        private System.Threading.SendOrPostCallback onCalculateNpvCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public NpvServiceClient() {
        }
        
        public NpvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NpvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NpvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetRandomDataCompletedEventArgs> GetRandomDataCompleted;
        
        public event System.EventHandler<CalculateNpvCompletedEventArgs> CalculateNpvCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService.BeginGetRandomData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRandomData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<double> CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService.EndGetRandomData(System.IAsyncResult result) {
            return base.Channel.EndGetRandomData(result);
        }
        
        private System.IAsyncResult OnBeginGetRandomData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService)(this)).BeginGetRandomData(callback, asyncState);
        }
        
        private object[] OnEndGetRandomData(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<double> retVal = ((CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService)(this)).EndGetRandomData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRandomDataCompleted(object state) {
            if ((this.GetRandomDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRandomDataCompleted(this, new GetRandomDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRandomDataAsync() {
            this.GetRandomDataAsync(null);
        }
        
        public void GetRandomDataAsync(object userState) {
            if ((this.onBeginGetRandomDataDelegate == null)) {
                this.onBeginGetRandomDataDelegate = new BeginOperationDelegate(this.OnBeginGetRandomData);
            }
            if ((this.onEndGetRandomDataDelegate == null)) {
                this.onEndGetRandomDataDelegate = new EndOperationDelegate(this.OnEndGetRandomData);
            }
            if ((this.onGetRandomDataCompletedDelegate == null)) {
                this.onGetRandomDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRandomDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetRandomDataDelegate, null, this.onEndGetRandomDataDelegate, this.onGetRandomDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService.BeginCalculateNpv(System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData, double rate, CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType, bool useXnpvFormula, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalculateNpv(npvData, rate, rolloverType, useXnpvFormula, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        double CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService.EndCalculateNpv(System.IAsyncResult result) {
            return base.Channel.EndCalculateNpv(result);
        }
        
        private System.IAsyncResult OnBeginCalculateNpv(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData = ((System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData>)(inValues[0]));
            double rate = ((double)(inValues[1]));
            CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType = ((CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType)(inValues[2]));
            bool useXnpvFormula = ((bool)(inValues[3]));
            return ((CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService)(this)).BeginCalculateNpv(npvData, rate, rolloverType, useXnpvFormula, callback, asyncState);
        }
        
        private object[] OnEndCalculateNpv(System.IAsyncResult result) {
            double retVal = ((CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService)(this)).EndCalculateNpv(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalculateNpvCompleted(object state) {
            if ((this.CalculateNpvCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalculateNpvCompleted(this, new CalculateNpvCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalculateNpvAsync(System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData, double rate, CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType, bool useXnpvFormula) {
            this.CalculateNpvAsync(npvData, rate, rolloverType, useXnpvFormula, null);
        }
        
        public void CalculateNpvAsync(System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData, double rate, CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType, bool useXnpvFormula, object userState) {
            if ((this.onBeginCalculateNpvDelegate == null)) {
                this.onBeginCalculateNpvDelegate = new BeginOperationDelegate(this.OnBeginCalculateNpv);
            }
            if ((this.onEndCalculateNpvDelegate == null)) {
                this.onEndCalculateNpvDelegate = new EndOperationDelegate(this.OnEndCalculateNpv);
            }
            if ((this.onCalculateNpvCompletedDelegate == null)) {
                this.onCalculateNpvCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalculateNpvCompleted);
            }
            base.InvokeAsync(this.onBeginCalculateNpvDelegate, new object[] {
                        npvData,
                        rate,
                        rolloverType,
                        useXnpvFormula}, this.onEndCalculateNpvDelegate, this.onCalculateNpvCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService CreateChannel() {
            return new NpvServiceClientChannel(this);
        }
        
        private class NpvServiceClientChannel : ChannelBase<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService>, CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService {
            
            public NpvServiceClientChannel(System.ServiceModel.ClientBase<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetRandomData(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRandomData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<double> EndGetRandomData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<double> _result = ((System.Collections.ObjectModel.ObservableCollection<double>)(base.EndInvoke("GetRandomData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCalculateNpv(System.Collections.ObjectModel.ObservableCollection<CiaranONeill.NPV.Silverlight.NpvServiceReference.NpvData> npvData, double rate, CiaranONeill.NPV.Silverlight.NpvServiceReference.RolloverType rolloverType, bool useXnpvFormula, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = npvData;
                _args[1] = rate;
                _args[2] = rolloverType;
                _args[3] = useXnpvFormula;
                System.IAsyncResult _result = base.BeginInvoke("CalculateNpv", _args, callback, asyncState);
                return _result;
            }
            
            public double EndCalculateNpv(System.IAsyncResult result) {
                object[] _args = new object[0];
                double _result = ((double)(base.EndInvoke("CalculateNpv", _args, result)));
                return _result;
            }
        }
    }
}
